sudo apt install ninja-build -y
sudo apt install libasound2-dev -y
sudo apt install libavcodec-dev -y
sudo apt install libavformat-dev -y
sudo apt install libavutil-dev -y
sudo apt install libcurl4-openssl-dev -y
sudo apt install libgtk-3-dev -y
sudo apt install libgif-dev -y
sudo apt install libglu1-mesa-dev -y
sudo apt install libharfbuzz-dev -y
sudo apt install libmpg123-dev -y
sudo apt install libopus-dev -y
sudo apt install libopusfile-dev -y
sudo apt install libsoundtouch-dev -y
sudo apt install libswresample-dev -y
sudo apt install libtiff-dev -y
sudo apt install libturbojpeg0-dev -y
sudo apt install libvorbis-dev -y
sudo apt install libwebp-dev -y
sudo apt install libxft-dev -y
sudo apt install uuid-dev -y
sudo apt install xorg-dev -y